// <auto-generated />
using DanskeWebApp.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DanskeWebApp.Migrations
{
    [DbContext(typeof(ArrayAnalysisDbContext))]
    partial class ArrayAnalysisDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DanskeWebApp.Model.AnalyzedArrays", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArrayComposition")
                        .HasColumnType("varchar(MAX)");

                    b.Property<int>("IsReachable")
                        .HasColumnType("int");

                    b.Property<string>("OptimalPath")
                        .HasColumnType("varchar(MAX)");

                    b.HasKey("Id");

                    b.ToTable("AnalyzedArrays");
                });
#pragma warning restore 612, 618
        }
    }
}
